/********************************************************************************
** Form generated from reading UI file 'server.ui'
**
** Created by: Qt User Interface Compiler version 5.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SERVER_H
#define UI_SERVER_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>

QT_BEGIN_NAMESPACE

class Ui_Server
{
public:
    QGroupBox *outer;
    QGroupBox *groupBox_0;
    QLabel *label_2;
    QLabel *stateLabel_0;
    QLabel *label_3;
    QLabel *curTmpLabel_0;
    QLabel *label_4;
    QLabel *tgTmpLabel_0;
    QLabel *label_5;
    QLabel *fanLabel_0;
    QLabel *label_6;
    QLabel *elecLabel_0;
    QLabel *label_7;
    QLabel *chargeLabel_0;
    QGroupBox *groupBox_1;
    QLabel *label_14;
    QLabel *stateLabel_1;
    QLabel *label_15;
    QLabel *curTmpLabel_1;
    QLabel *label_16;
    QLabel *tgTmpLabel_1;
    QLabel *label_17;
    QLabel *fanLabel_1;
    QLabel *label_18;
    QLabel *elecLabel_1;
    QLabel *label_19;
    QLabel *chargeLabel_1;
    QGroupBox *groupBox_2;
    QLabel *label_20;
    QLabel *stateLabel_2;
    QLabel *label_21;
    QLabel *curTmpLabel_2;
    QLabel *label_22;
    QLabel *tgTmpLabel_2;
    QLabel *label_23;
    QLabel *fanLabel_2;
    QLabel *label_24;
    QLabel *elecLabel_2;
    QLabel *label_25;
    QLabel *chargeLabel_2;
    QGroupBox *groupBox_3;
    QLabel *label_50;
    QLabel *stateLabel_3;
    QLabel *label_51;
    QLabel *curTmpLabel_3;
    QLabel *label_52;
    QLabel *tgTmpLabel_3;
    QLabel *label_53;
    QLabel *fanLabel_3;
    QLabel *label_54;
    QLabel *elecLabel_3;
    QLabel *label_55;
    QLabel *chargeLabel_3;
    QGroupBox *groupBox_4;
    QLabel *label_56;
    QLabel *stateLabel_4;
    QLabel *label_57;
    QLabel *curTmpLabel_4;
    QLabel *label_58;
    QLabel *tgTmpLabel_4;
    QLabel *label_59;
    QLabel *fanLabel_4;
    QLabel *label_60;
    QLabel *elecLabel_4;
    QLabel *label_61;
    QLabel *chargeLabel_4;
    QGroupBox *groupBox_7;
    QLabel *label_62;
    QLabel *stateLabel_7;
    QLabel *label_63;
    QLabel *curTmpLabel_7;
    QLabel *label_64;
    QLabel *tgTmpLabel_7;
    QLabel *label_65;
    QLabel *fanLabel_7;
    QLabel *label_66;
    QLabel *elecLabel_7;
    QLabel *label_67;
    QLabel *chargeLabel_7;
    QGroupBox *groupBox_9;
    QLabel *label_68;
    QLabel *stateLabel_9;
    QLabel *label_69;
    QLabel *curTmpLabel_9;
    QLabel *label_70;
    QLabel *tgTmpLabel_9;
    QLabel *label_71;
    QLabel *fanLabel_9;
    QLabel *label_72;
    QLabel *elecLabel_9;
    QLabel *label_73;
    QLabel *chargeLabel_9;
    QGroupBox *groupBox_6;
    QLabel *label_74;
    QLabel *stateLabel_6;
    QLabel *label_75;
    QLabel *curTmpLabel_6;
    QLabel *label_76;
    QLabel *tgTmpLabel_6;
    QLabel *label_77;
    QLabel *fanLabel_6;
    QLabel *label_78;
    QLabel *elecLabel_6;
    QLabel *label_79;
    QLabel *chargeLabel_6;
    QGroupBox *groupBox_5;
    QLabel *label_80;
    QLabel *stateLabel_5;
    QLabel *label_81;
    QLabel *curTmpLabel_5;
    QLabel *label_82;
    QLabel *tgTmpLabel_5;
    QLabel *label_83;
    QLabel *fanLabel_5;
    QLabel *label_84;
    QLabel *elecLabel_5;
    QLabel *label_85;
    QLabel *chargeLabel_5;
    QGroupBox *groupBox_8;
    QLabel *label_86;
    QLabel *stateLabel_8;
    QLabel *label_87;
    QLabel *curTmpLabel_8;
    QLabel *label_88;
    QLabel *tgTmpLabel_8;
    QLabel *label_89;
    QLabel *fanLabel_8;
    QLabel *label_90;
    QLabel *elecLabel_8;
    QLabel *label_91;
    QLabel *chargeLabel_8;

    void setupUi(QDialog *Server)
    {
        if (Server->objectName().isEmpty())
            Server->setObjectName(QStringLiteral("Server"));
        Server->resize(894, 632);
        outer = new QGroupBox(Server);
        outer->setObjectName(QStringLiteral("outer"));
        outer->setGeometry(QRect(10, 10, 861, 511));
        groupBox_0 = new QGroupBox(outer);
        groupBox_0->setObjectName(QStringLiteral("groupBox_0"));
        groupBox_0->setGeometry(QRect(30, 30, 151, 221));
        label_2 = new QLabel(groupBox_0);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 30, 54, 16));
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_0 = new QLabel(groupBox_0);
        stateLabel_0->setObjectName(QStringLiteral("stateLabel_0"));
        stateLabel_0->setGeometry(QRect(70, 30, 71, 16));
        label_3 = new QLabel(groupBox_0);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 60, 54, 16));
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_0 = new QLabel(groupBox_0);
        curTmpLabel_0->setObjectName(QStringLiteral("curTmpLabel_0"));
        curTmpLabel_0->setGeometry(QRect(70, 60, 71, 16));
        label_4 = new QLabel(groupBox_0);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 90, 54, 16));
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_0 = new QLabel(groupBox_0);
        tgTmpLabel_0->setObjectName(QStringLiteral("tgTmpLabel_0"));
        tgTmpLabel_0->setGeometry(QRect(70, 90, 71, 16));
        label_5 = new QLabel(groupBox_0);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 120, 54, 16));
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_0 = new QLabel(groupBox_0);
        fanLabel_0->setObjectName(QStringLiteral("fanLabel_0"));
        fanLabel_0->setGeometry(QRect(70, 120, 71, 16));
        label_6 = new QLabel(groupBox_0);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 150, 54, 16));
        label_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_0 = new QLabel(groupBox_0);
        elecLabel_0->setObjectName(QStringLiteral("elecLabel_0"));
        elecLabel_0->setGeometry(QRect(70, 150, 71, 16));
        label_7 = new QLabel(groupBox_0);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 180, 54, 16));
        label_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_0 = new QLabel(groupBox_0);
        chargeLabel_0->setObjectName(QStringLiteral("chargeLabel_0"));
        chargeLabel_0->setGeometry(QRect(70, 180, 71, 16));
        groupBox_1 = new QGroupBox(outer);
        groupBox_1->setObjectName(QStringLiteral("groupBox_1"));
        groupBox_1->setGeometry(QRect(190, 30, 151, 221));
        label_14 = new QLabel(groupBox_1);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 30, 54, 16));
        label_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_1 = new QLabel(groupBox_1);
        stateLabel_1->setObjectName(QStringLiteral("stateLabel_1"));
        stateLabel_1->setGeometry(QRect(70, 30, 71, 16));
        label_15 = new QLabel(groupBox_1);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 60, 54, 16));
        label_15->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_1 = new QLabel(groupBox_1);
        curTmpLabel_1->setObjectName(QStringLiteral("curTmpLabel_1"));
        curTmpLabel_1->setGeometry(QRect(70, 60, 71, 16));
        label_16 = new QLabel(groupBox_1);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 90, 54, 16));
        label_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_1 = new QLabel(groupBox_1);
        tgTmpLabel_1->setObjectName(QStringLiteral("tgTmpLabel_1"));
        tgTmpLabel_1->setGeometry(QRect(70, 90, 71, 16));
        label_17 = new QLabel(groupBox_1);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 120, 54, 16));
        label_17->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_1 = new QLabel(groupBox_1);
        fanLabel_1->setObjectName(QStringLiteral("fanLabel_1"));
        fanLabel_1->setGeometry(QRect(70, 120, 71, 16));
        label_18 = new QLabel(groupBox_1);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 150, 54, 16));
        label_18->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_1 = new QLabel(groupBox_1);
        elecLabel_1->setObjectName(QStringLiteral("elecLabel_1"));
        elecLabel_1->setGeometry(QRect(70, 150, 71, 16));
        label_19 = new QLabel(groupBox_1);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 180, 54, 16));
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_1 = new QLabel(groupBox_1);
        chargeLabel_1->setObjectName(QStringLiteral("chargeLabel_1"));
        chargeLabel_1->setGeometry(QRect(70, 180, 71, 16));
        groupBox_2 = new QGroupBox(outer);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(350, 30, 151, 221));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 30, 54, 16));
        label_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_2 = new QLabel(groupBox_2);
        stateLabel_2->setObjectName(QStringLiteral("stateLabel_2"));
        stateLabel_2->setGeometry(QRect(70, 30, 71, 16));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 60, 54, 16));
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_2 = new QLabel(groupBox_2);
        curTmpLabel_2->setObjectName(QStringLiteral("curTmpLabel_2"));
        curTmpLabel_2->setGeometry(QRect(70, 60, 71, 16));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 90, 54, 16));
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_2 = new QLabel(groupBox_2);
        tgTmpLabel_2->setObjectName(QStringLiteral("tgTmpLabel_2"));
        tgTmpLabel_2->setGeometry(QRect(70, 90, 71, 16));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 120, 54, 16));
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_2 = new QLabel(groupBox_2);
        fanLabel_2->setObjectName(QStringLiteral("fanLabel_2"));
        fanLabel_2->setGeometry(QRect(70, 120, 71, 16));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 150, 54, 16));
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_2 = new QLabel(groupBox_2);
        elecLabel_2->setObjectName(QStringLiteral("elecLabel_2"));
        elecLabel_2->setGeometry(QRect(70, 150, 71, 16));
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(10, 180, 54, 16));
        label_25->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_2 = new QLabel(groupBox_2);
        chargeLabel_2->setObjectName(QStringLiteral("chargeLabel_2"));
        chargeLabel_2->setGeometry(QRect(70, 180, 71, 16));
        groupBox_3 = new QGroupBox(outer);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(510, 30, 151, 221));
        label_50 = new QLabel(groupBox_3);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(10, 30, 54, 16));
        label_50->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_3 = new QLabel(groupBox_3);
        stateLabel_3->setObjectName(QStringLiteral("stateLabel_3"));
        stateLabel_3->setGeometry(QRect(70, 30, 71, 16));
        label_51 = new QLabel(groupBox_3);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(10, 60, 54, 16));
        label_51->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_3 = new QLabel(groupBox_3);
        curTmpLabel_3->setObjectName(QStringLiteral("curTmpLabel_3"));
        curTmpLabel_3->setGeometry(QRect(70, 60, 71, 16));
        label_52 = new QLabel(groupBox_3);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(10, 90, 54, 16));
        label_52->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_3 = new QLabel(groupBox_3);
        tgTmpLabel_3->setObjectName(QStringLiteral("tgTmpLabel_3"));
        tgTmpLabel_3->setGeometry(QRect(70, 90, 71, 16));
        label_53 = new QLabel(groupBox_3);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 120, 54, 16));
        label_53->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_3 = new QLabel(groupBox_3);
        fanLabel_3->setObjectName(QStringLiteral("fanLabel_3"));
        fanLabel_3->setGeometry(QRect(70, 120, 71, 16));
        label_54 = new QLabel(groupBox_3);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(10, 150, 54, 16));
        label_54->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_3 = new QLabel(groupBox_3);
        elecLabel_3->setObjectName(QStringLiteral("elecLabel_3"));
        elecLabel_3->setGeometry(QRect(70, 150, 71, 16));
        label_55 = new QLabel(groupBox_3);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(10, 180, 54, 16));
        label_55->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_3 = new QLabel(groupBox_3);
        chargeLabel_3->setObjectName(QStringLiteral("chargeLabel_3"));
        chargeLabel_3->setGeometry(QRect(70, 180, 71, 16));
        groupBox_4 = new QGroupBox(outer);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(670, 30, 151, 221));
        label_56 = new QLabel(groupBox_4);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 30, 54, 16));
        label_56->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_4 = new QLabel(groupBox_4);
        stateLabel_4->setObjectName(QStringLiteral("stateLabel_4"));
        stateLabel_4->setGeometry(QRect(70, 30, 71, 16));
        label_57 = new QLabel(groupBox_4);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(10, 60, 54, 16));
        label_57->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_4 = new QLabel(groupBox_4);
        curTmpLabel_4->setObjectName(QStringLiteral("curTmpLabel_4"));
        curTmpLabel_4->setGeometry(QRect(70, 60, 71, 16));
        label_58 = new QLabel(groupBox_4);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(10, 90, 54, 16));
        label_58->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_4 = new QLabel(groupBox_4);
        tgTmpLabel_4->setObjectName(QStringLiteral("tgTmpLabel_4"));
        tgTmpLabel_4->setGeometry(QRect(70, 90, 71, 16));
        label_59 = new QLabel(groupBox_4);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(10, 120, 54, 16));
        label_59->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_4 = new QLabel(groupBox_4);
        fanLabel_4->setObjectName(QStringLiteral("fanLabel_4"));
        fanLabel_4->setGeometry(QRect(70, 120, 71, 16));
        label_60 = new QLabel(groupBox_4);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(10, 150, 54, 16));
        label_60->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_4 = new QLabel(groupBox_4);
        elecLabel_4->setObjectName(QStringLiteral("elecLabel_4"));
        elecLabel_4->setGeometry(QRect(70, 150, 71, 16));
        label_61 = new QLabel(groupBox_4);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(10, 180, 54, 16));
        label_61->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_4 = new QLabel(groupBox_4);
        chargeLabel_4->setObjectName(QStringLiteral("chargeLabel_4"));
        chargeLabel_4->setGeometry(QRect(70, 180, 71, 16));
        groupBox_7 = new QGroupBox(outer);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(350, 260, 151, 221));
        label_62 = new QLabel(groupBox_7);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(10, 30, 54, 16));
        label_62->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_7 = new QLabel(groupBox_7);
        stateLabel_7->setObjectName(QStringLiteral("stateLabel_7"));
        stateLabel_7->setGeometry(QRect(70, 30, 71, 16));
        label_63 = new QLabel(groupBox_7);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(10, 60, 54, 16));
        label_63->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_7 = new QLabel(groupBox_7);
        curTmpLabel_7->setObjectName(QStringLiteral("curTmpLabel_7"));
        curTmpLabel_7->setGeometry(QRect(70, 60, 71, 16));
        label_64 = new QLabel(groupBox_7);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(10, 90, 54, 16));
        label_64->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_7 = new QLabel(groupBox_7);
        tgTmpLabel_7->setObjectName(QStringLiteral("tgTmpLabel_7"));
        tgTmpLabel_7->setGeometry(QRect(70, 90, 71, 16));
        label_65 = new QLabel(groupBox_7);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(10, 120, 54, 16));
        label_65->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_7 = new QLabel(groupBox_7);
        fanLabel_7->setObjectName(QStringLiteral("fanLabel_7"));
        fanLabel_7->setGeometry(QRect(70, 120, 71, 16));
        label_66 = new QLabel(groupBox_7);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(10, 150, 54, 16));
        label_66->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_7 = new QLabel(groupBox_7);
        elecLabel_7->setObjectName(QStringLiteral("elecLabel_7"));
        elecLabel_7->setGeometry(QRect(70, 150, 71, 16));
        label_67 = new QLabel(groupBox_7);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(10, 180, 54, 16));
        label_67->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_7 = new QLabel(groupBox_7);
        chargeLabel_7->setObjectName(QStringLiteral("chargeLabel_7"));
        chargeLabel_7->setGeometry(QRect(70, 180, 71, 16));
        groupBox_9 = new QGroupBox(outer);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(670, 260, 151, 221));
        label_68 = new QLabel(groupBox_9);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(10, 30, 54, 16));
        label_68->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_9 = new QLabel(groupBox_9);
        stateLabel_9->setObjectName(QStringLiteral("stateLabel_9"));
        stateLabel_9->setGeometry(QRect(70, 30, 71, 16));
        label_69 = new QLabel(groupBox_9);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(10, 60, 54, 16));
        label_69->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_9 = new QLabel(groupBox_9);
        curTmpLabel_9->setObjectName(QStringLiteral("curTmpLabel_9"));
        curTmpLabel_9->setGeometry(QRect(70, 60, 71, 16));
        label_70 = new QLabel(groupBox_9);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(10, 90, 54, 16));
        label_70->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_9 = new QLabel(groupBox_9);
        tgTmpLabel_9->setObjectName(QStringLiteral("tgTmpLabel_9"));
        tgTmpLabel_9->setGeometry(QRect(70, 90, 71, 16));
        label_71 = new QLabel(groupBox_9);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(10, 120, 54, 16));
        label_71->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_9 = new QLabel(groupBox_9);
        fanLabel_9->setObjectName(QStringLiteral("fanLabel_9"));
        fanLabel_9->setGeometry(QRect(70, 120, 71, 16));
        label_72 = new QLabel(groupBox_9);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(10, 150, 54, 16));
        label_72->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_9 = new QLabel(groupBox_9);
        elecLabel_9->setObjectName(QStringLiteral("elecLabel_9"));
        elecLabel_9->setGeometry(QRect(70, 150, 71, 16));
        label_73 = new QLabel(groupBox_9);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(10, 180, 54, 16));
        label_73->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_9 = new QLabel(groupBox_9);
        chargeLabel_9->setObjectName(QStringLiteral("chargeLabel_9"));
        chargeLabel_9->setGeometry(QRect(70, 180, 71, 16));
        groupBox_6 = new QGroupBox(outer);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(190, 260, 151, 221));
        label_74 = new QLabel(groupBox_6);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(10, 30, 54, 16));
        label_74->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_6 = new QLabel(groupBox_6);
        stateLabel_6->setObjectName(QStringLiteral("stateLabel_6"));
        stateLabel_6->setGeometry(QRect(70, 30, 71, 16));
        label_75 = new QLabel(groupBox_6);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(10, 60, 54, 16));
        label_75->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_6 = new QLabel(groupBox_6);
        curTmpLabel_6->setObjectName(QStringLiteral("curTmpLabel_6"));
        curTmpLabel_6->setGeometry(QRect(70, 60, 71, 16));
        label_76 = new QLabel(groupBox_6);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(10, 90, 54, 16));
        label_76->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_6 = new QLabel(groupBox_6);
        tgTmpLabel_6->setObjectName(QStringLiteral("tgTmpLabel_6"));
        tgTmpLabel_6->setGeometry(QRect(70, 90, 71, 16));
        label_77 = new QLabel(groupBox_6);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(10, 120, 54, 16));
        label_77->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_6 = new QLabel(groupBox_6);
        fanLabel_6->setObjectName(QStringLiteral("fanLabel_6"));
        fanLabel_6->setGeometry(QRect(70, 120, 71, 16));
        label_78 = new QLabel(groupBox_6);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(10, 150, 54, 16));
        label_78->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_6 = new QLabel(groupBox_6);
        elecLabel_6->setObjectName(QStringLiteral("elecLabel_6"));
        elecLabel_6->setGeometry(QRect(70, 150, 71, 16));
        label_79 = new QLabel(groupBox_6);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(10, 180, 54, 16));
        label_79->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_6 = new QLabel(groupBox_6);
        chargeLabel_6->setObjectName(QStringLiteral("chargeLabel_6"));
        chargeLabel_6->setGeometry(QRect(70, 180, 71, 16));
        groupBox_5 = new QGroupBox(outer);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(30, 260, 151, 221));
        label_80 = new QLabel(groupBox_5);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(10, 30, 54, 16));
        label_80->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_5 = new QLabel(groupBox_5);
        stateLabel_5->setObjectName(QStringLiteral("stateLabel_5"));
        stateLabel_5->setGeometry(QRect(70, 30, 71, 16));
        label_81 = new QLabel(groupBox_5);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(10, 60, 54, 16));
        label_81->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_5 = new QLabel(groupBox_5);
        curTmpLabel_5->setObjectName(QStringLiteral("curTmpLabel_5"));
        curTmpLabel_5->setGeometry(QRect(70, 60, 71, 16));
        label_82 = new QLabel(groupBox_5);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(10, 90, 54, 16));
        label_82->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_5 = new QLabel(groupBox_5);
        tgTmpLabel_5->setObjectName(QStringLiteral("tgTmpLabel_5"));
        tgTmpLabel_5->setGeometry(QRect(70, 90, 71, 16));
        label_83 = new QLabel(groupBox_5);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(10, 120, 54, 16));
        label_83->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_5 = new QLabel(groupBox_5);
        fanLabel_5->setObjectName(QStringLiteral("fanLabel_5"));
        fanLabel_5->setGeometry(QRect(70, 120, 71, 16));
        label_84 = new QLabel(groupBox_5);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(10, 150, 54, 16));
        label_84->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_5 = new QLabel(groupBox_5);
        elecLabel_5->setObjectName(QStringLiteral("elecLabel_5"));
        elecLabel_5->setGeometry(QRect(70, 150, 71, 16));
        label_85 = new QLabel(groupBox_5);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(10, 180, 54, 16));
        label_85->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_5 = new QLabel(groupBox_5);
        chargeLabel_5->setObjectName(QStringLiteral("chargeLabel_5"));
        chargeLabel_5->setGeometry(QRect(70, 180, 71, 16));
        groupBox_8 = new QGroupBox(outer);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(510, 260, 151, 221));
        label_86 = new QLabel(groupBox_8);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(10, 30, 54, 16));
        label_86->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        stateLabel_8 = new QLabel(groupBox_8);
        stateLabel_8->setObjectName(QStringLiteral("stateLabel_8"));
        stateLabel_8->setGeometry(QRect(70, 30, 71, 16));
        label_87 = new QLabel(groupBox_8);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(10, 60, 54, 16));
        label_87->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        curTmpLabel_8 = new QLabel(groupBox_8);
        curTmpLabel_8->setObjectName(QStringLiteral("curTmpLabel_8"));
        curTmpLabel_8->setGeometry(QRect(70, 60, 71, 16));
        label_88 = new QLabel(groupBox_8);
        label_88->setObjectName(QStringLiteral("label_88"));
        label_88->setGeometry(QRect(10, 90, 54, 16));
        label_88->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tgTmpLabel_8 = new QLabel(groupBox_8);
        tgTmpLabel_8->setObjectName(QStringLiteral("tgTmpLabel_8"));
        tgTmpLabel_8->setGeometry(QRect(70, 90, 71, 16));
        label_89 = new QLabel(groupBox_8);
        label_89->setObjectName(QStringLiteral("label_89"));
        label_89->setGeometry(QRect(10, 120, 54, 16));
        label_89->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fanLabel_8 = new QLabel(groupBox_8);
        fanLabel_8->setObjectName(QStringLiteral("fanLabel_8"));
        fanLabel_8->setGeometry(QRect(70, 120, 71, 16));
        label_90 = new QLabel(groupBox_8);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(10, 150, 54, 16));
        label_90->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        elecLabel_8 = new QLabel(groupBox_8);
        elecLabel_8->setObjectName(QStringLiteral("elecLabel_8"));
        elecLabel_8->setGeometry(QRect(70, 150, 71, 16));
        label_91 = new QLabel(groupBox_8);
        label_91->setObjectName(QStringLiteral("label_91"));
        label_91->setGeometry(QRect(10, 180, 54, 16));
        label_91->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        chargeLabel_8 = new QLabel(groupBox_8);
        chargeLabel_8->setObjectName(QStringLiteral("chargeLabel_8"));
        chargeLabel_8->setGeometry(QRect(70, 180, 71, 16));

        retranslateUi(Server);

        QMetaObject::connectSlotsByName(Server);
    } // setupUi

    void retranslateUi(QDialog *Server)
    {
        Server->setWindowTitle(QApplication::translate("Server", "Dialog", nullptr));
        outer->setTitle(QApplication::translate("Server", "\347\233\221\346\216\247", nullptr));
        groupBox_0->setTitle(QApplication::translate("Server", "306C", nullptr));
        label_2->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_0->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_3->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_0->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_4->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_0->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_5->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_0->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_6->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_0->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_7->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_0->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_1->setTitle(QApplication::translate("Server", "306D", nullptr));
        label_14->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_1->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_15->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_1->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_16->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_1->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_17->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_1->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_18->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_1->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_19->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_1->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_2->setTitle(QApplication::translate("Server", "307C", nullptr));
        label_20->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_2->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_21->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_2->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_22->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_2->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_23->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_2->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_24->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_2->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_25->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_2->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_3->setTitle(QApplication::translate("Server", "307D", nullptr));
        label_50->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_3->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_51->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_3->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_52->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_3->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_53->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_3->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_54->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_3->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_55->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_3->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_4->setTitle(QApplication::translate("Server", "308C", nullptr));
        label_56->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_4->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_57->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_4->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_58->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_4->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_59->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_4->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_60->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_4->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_61->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_4->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_7->setTitle(QApplication::translate("Server", "309D", nullptr));
        label_62->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_7->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_63->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_7->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_64->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_7->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_65->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_7->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_66->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_7->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_67->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_7->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_9->setTitle(QApplication::translate("Server", "310D", nullptr));
        label_68->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_9->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_69->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_9->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_70->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_9->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_71->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_9->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_72->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_9->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_73->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_9->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_6->setTitle(QApplication::translate("Server", "309C", nullptr));
        label_74->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_6->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_75->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_6->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_76->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_6->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_77->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_6->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_78->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_6->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_79->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_6->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_5->setTitle(QApplication::translate("Server", "308D", nullptr));
        label_80->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_5->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_81->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_5->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_82->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_5->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_83->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_5->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_84->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_5->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_85->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_5->setText(QApplication::translate("Server", "TextLabel", nullptr));
        groupBox_8->setTitle(QApplication::translate("Server", "310C", nullptr));
        label_86->setText(QApplication::translate("Server", "\347\212\266\346\200\201", nullptr));
        stateLabel_8->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_87->setText(QApplication::translate("Server", "\345\275\223\345\211\215\346\270\251\345\272\246", nullptr));
        curTmpLabel_8->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_88->setText(QApplication::translate("Server", "\347\233\256\346\240\207\346\270\251\345\272\246", nullptr));
        tgTmpLabel_8->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_89->setText(QApplication::translate("Server", "\351\243\216\351\200\237", nullptr));
        fanLabel_8->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_90->setText(QApplication::translate("Server", "\350\200\227\347\224\265\351\207\217", nullptr));
        elecLabel_8->setText(QApplication::translate("Server", "TextLabel", nullptr));
        label_91->setText(QApplication::translate("Server", "\350\264\271\347\224\250", nullptr));
        chargeLabel_8->setText(QApplication::translate("Server", "TextLabel", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Server: public Ui_Server {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SERVER_H
